#!/bin/bash
# /etc/init.d/chezmoi

### BEGIN INIT INFO
# Provides:          chezmoi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: chezmoi hub
# Description:       chezmoi hub
### END INIT INFO

HUB_HOME=/home/pi/chezmoi/hub

case "$1" in
    start)
        echo "Starting chezmoi hub"
	    cd $HUB_HOME; sudo -u pi npm start > /dev/null 2>&1 &
        ;;
    stop)
	    pkill -f 'node index.js'
	    echo 'Stopped chezmoi'
        ;;
    *)
        echo "Usage: /etc/init.d/chezmoi start|stop"
        exit 1
        ;;
esac

exit 0

